name: CI-MultiOS

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [macos-latest, arm64, bash],
          [macos-13, x86_64, bash],
          [ubuntu-latest, x86_64, bash],
          [windows-latest, x86_64, msys2]
        ]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[2] }} {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install Ubuntu packages
        if: matrix.os[0] == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install curl make bash

      - name: Install macOS packages
        if: startsWith(matrix.os[0], 'macos')
        run: |
          brew update
          brew install curl make bash md5sha1sum

      - name: Install MSYS2 packages
        if: matrix.os[0] == 'windows-latest'  
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: |
            base-devel git mingw-w64-i686-gcc tar mingw-w64-i686-cmake mingw-w64-i686-make
          update: true

      - name: Compile project
        run: |
          gcc -o bin2c bin2c.c
          ./bin2c mcman.irx mcman_irx.c mcman_irx
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: mcman_irx-${{ steps.slug.outputs.sha8 }}-${{matrix.os[0]}}-${{matrix.os[1]}}
          path: mcman_irx.c
  